import magik.createGithubPublication
import magik.github

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    kotlin("jvm") version embeddedKotlinVersion

    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    id("elect86.magik") version "0.2.0"
    `maven-publish`

    application
}

version = "0.0.1"
group = "elect86"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

application {
    //    mainClass.set("slurm.MiscKt")
    //    mainClass.set("slurm.NodesKt")
    //    mainClass.set("slurm.SqueueKt")
}

dependencies {

//    implementation("org.gradle:gradle-tooling-api:7.3-20210825160000+0000")

    implementation("com.github.ajalt.mordant:mordant:2.0.0-beta2")
    implementation("com.github.ajalt.mordant:mordant-jvm:2.0.0-beta2")

    // Align versions of all Kotlin components
    implementation(platform(kotlin("bom", embeddedKotlinVersion)))

    // Use the Kotlin JDK 8 standard library.
    implementation(kotlin("stdlib-jdk8"))

    // Use the Kotlin test library.
    testImplementation(kotlin("test"))

    // Use the Kotlin JUnit integration.
    //    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

tasks {

    test { useJUnitPlatform() }

}

publishing {
    publications {
        createGithubPublication {
            from(components["java"])
            //    artifact(sourceJar)
        }
        repositories {
            github {
                domain = "kotlin-graphics/mary"
            }
        }
    }
}